[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "20.10.0"
  NPM_VERSION = "10.2.3"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
