[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "20.10.0"
  NPM_VERSION = "10.2.3"
  NEXT_USE_NETLIFY_EDGE = "true"

# Configuração para SPA (Single Page Application)
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Configuração para fallback de rotas
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Configuração para funções serverless
[functions]
  node_bundler = "esbuild"
  included_files = ["out/_next/static/**"]

# Configuração de cabeçalhos para cache
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
